---
title: "Carrera De La Luz 2022"
subtile: "Actividad 1 - Métodos y Simulación Estadística"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#FFFFFF"
      fg: "#000000" 
      primary: "#FFA500" 
      base_font:
        google: Sen
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(ggplot2)
library(paqueteMET)

data("CarreraLuz22")

  
Theme2 = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 8),
  axis.title.y = element_text(size = 8),
  # axis.text.y = element_blank(),
  axis.text = element_text( size = 8),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8),  
  strip.text = element_text(size=8),
  title =element_text(size=8, face='bold')
)# tamaño letra por grupos

# subsets-----------------------------------------------------------------------
CarreraLuz22$sex[CarreraLuz22$sex == "M"]="Hombre"
CarreraLuz22$sex[CarreraLuz22$sex == "F"]="Mujer"
#-------------------------------------------------------------------------------
CarreraLuz22M = subset(CarreraLuz22, CarreraLuz22$sex=="Hombre")
CarreraLuz22F = subset(CarreraLuz22, CarreraLuz22$sex=="Mujer")

#-------------------------------------------------------------------------------
CarreraLuz22_c1M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="1. Juvenil")
CarreraLuz22_c2M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="2. Abierta")
CarreraLuz22_c3M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="3. Veteranos A")
CarreraLuz22_c4M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="4. Veteranos B")
CarreraLuz22_c5M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="5. Veteranos C")


CarreraLuz22_c1F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="1. Juvenil")
CarreraLuz22_c2F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="2. Abierta")
CarreraLuz22_c3F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="3. Veteranos A")
CarreraLuz22_c4F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="4. Veteranos B")
CarreraLuz22_c5F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="5. Veteranos C")
#-------------------------------------------------------------------------------

categoria= c("Juvenil","Abierta","Veteranos A", "Veteranos B","Veteranos C")
t2 = aggregate(CarreraLuz22$timerun/60, by=list(CarreraLuz22$categoria,CarreraLuz22$sex), FUN= summary)
t2=t2$x
t2m=t2[1:5,] 
row.names(t2m)=categoria
t2h=t2[6:10,] 
row.names(t2h)=categoria
```

Column {data-width=700 .tabset}
-----------------------------------------------------------------------

### Porcentaje de Hombres y Mujeres

```{r}
paleta6=c("#FF00FF", "#800080", "#F6E271", "#F6B916", "#F69312", "#FF0000")


# Contar la frecuencia de cada valor en la variable sex
frecuencias_sex <- table(CarreraLuz22$sex)

# Calcular los porcentajes
porcentajes_sex <- prop.table(frecuencias_sex) * 100

# Crear un vector de colores para cada valor en la variable sex
colores_sex <- c("Hombre" = "#0000FF", "Mujer" = "#FF00FF")

# Crear el gráfico de pastel
p1=ggplot(data.frame(Sexo = names(porcentajes_sex), porcentajes = porcentajes_sex), aes(x = "", y = porcentajes_sex, fill = Sexo)) +
  geom_bar(width = 1, stat = "identity") +
  geom_text(aes(label = sprintf("%.1f%%", porcentajes_sex)), position = position_stack(vjust = 0.5)) +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = colores_sex) +
  labs(title = "",
       x = "",
       y = "Sexo (%)") +
  theme_minimal()




p1

```

### Tiempo de Hombres por Edad

```{r, fig.height=3}

# Agrupar la data frame por edad y calcular el promedio del timerun para cada edad
promedios_timerun_edad <- aggregate(timerun ~ edad, data = CarreraLuz22M, mean)

# Crear el gráfico de líneas
ggplot(promedios_timerun_edad, aes(x = edad, y = timerun/60)) +
  geom_line(color="#0000FF") +
  labs(x = "Edad",
       y = "Promedio del tiempo de carrera (min)") +
  theme_dark()

t2h
```

### Tiempo de Mujeres por Edad
```{r, fig.height=3}
# Agrupar la data frame por edad y calcular el promedio del timerun para cada edad
promedios_timerun_edad <- aggregate(timerun ~ edad, data = CarreraLuz22F, mean)

# Crear el gráfico de líneas
ggplot(promedios_timerun_edad, aes(x = edad, y = timerun/60)) +
  geom_line(color="#FF00FF") +
  labs(x = "Edad",
       y = "Promedio del tiempo de carrera (min)") +
  theme_dark()
t2m
```

### Edad por Género

```{r, fig.height=3}
ggplot(CarreraLuz22, aes(x=sex, y=edad, fill=sex)) +
  geom_boxplot() +
  xlab("Género") +
  ylab("Edad") +
  ggtitle("Distribución de la edad por género") +
  scale_fill_manual(values=c("#0000FF", "#FF00FF"))
```

Column {data-width=400}
-----------------------------------------------------------------------

### Frecuencia mujeres por categoría

```{r}
# Convertir la variable categoria en una variable categórica numérica
CarreraLuz22F$categoria_num <- as.numeric(factor(CarreraLuz22F$categoria))

# Crear el histograma de frecuencias de la variable categoria_num
# convertir la variable 'categoria' en una variable factor
CarreraLuz22F$categoria <- as.factor(CarreraLuz22F$categoria)

# contar las frecuencias de la variable 'categoria'
categoria_freq <- table(CarreraLuz22F$categoria)

# crear el gráfico de barras
ggplot(data.frame(categoria_freq), aes(x=Var1, y=Freq)) +
  geom_bar(stat="identity", fill = "#FF00FF") +
  xlab("Categoría") +
  ylab("Frecuencia") +
  ggtitle("")
```

### Frecuencia hombres por categoría

```{r}
# Convertir la variable categoria en una variable categórica numérica
CarreraLuz22M$categoria_num <- as.numeric(factor(CarreraLuz22M$categoria))

# Crear el histograma de frecuencias de la variable categoria_num
# convertir la variable 'categoria' en una variable factor
CarreraLuz22M$categoria <- as.factor(CarreraLuz22M$categoria)

# contar las frecuencias de la variable 'categoria'
categoria_freq <- table(CarreraLuz22M$categoria)

# crear el gráfico de barras
ggplot(data.frame(categoria_freq), aes(x=Var1, y=Freq)) +
  geom_bar(stat="identity", fill = "#0000FF") +
  xlab("Categoría") +
  ylab("Frecuencia") +
  ggtitle("")
```

Column { data-width=50 }
-----------------------------------------------------------------------
### hombres  {.value-box}
```{r}
valueBox(value =paste(length(CarreraLuz22M$id),"Hombres"), 
         caption = "Cantidad de Hombres", 
         icon = "", 
         color = "#FF0000")
```


### mujeres  {.value-box}
```{r}
valueBox(value =paste(length(CarreraLuz22F$id),"Mujeres"), 
         caption = "Cantidad de Mujeres", 
         icon = "",  
         color = "#FFA500")
```


### tiempoM  {.value-box}
```{r}
valueBox(value = paste(round(mean(CarreraLuz22M$timerun/60)),"min"), 
         caption = "Tiempo Promedio Hombres", 
         icon = "", 
         color = "#FFFF00")
```


### tiempoF  {.value-box}
```{r}
valueBox(value = paste(round(mean(CarreraLuz22F$timerun/60)),"min"), 
         caption = "Tiempo Promedio Mujeres", 
         icon = "",  
         color = "#00FF00")
```


### mejorM  {.value-box}
```{r}
valueBox(value = paste(round(min(CarreraLuz22M$timerun/60)),"min"), 
         caption = "Mejor Tiempo Hombres", 
         icon = "",   
         color = "#0000FF")
```

### mejorF  {.value-box}
```{r}
valueBox(value = paste(round(min(CarreraLuz22F$timerun/60)),"min"), 
         caption = "Mejor Tiempo Mujeres", 
         icon = "", 
         color = "#4B0082")
```

### peor  {.value-box}
```{r}
valueBox(value = paste(round(max(CarreraLuz22$timerun/60)),"min"), 
         caption = "Peor Tiempo", 
         icon = "",  
         color = "#9400D3")
